### ISSUE TITLE
ModuleNotFoundError: No module named 'Florence.VariationalPrinciple.DisplacementApproachIndices'

### ISSUE THREAD

**Issue by nicolaskr** [romeric/florence#7]
After easy install with pip (All the dependencies have been installed except PostMesh) the execution of " from Florence import * " provides an error:

File "/home/user/anaconda3/lib/python3.7/site-packages/Florence/__init__.py", line 6, in <module>
    from .VariationalPrinciple import *
  File "/home/user/anaconda3/lib/python3.7/site-packages/Florence/VariationalPrinciple/__init__.py", line 1, in <module>
    from .VariationalPrinciple import *
  File "/home/user/anaconda3/lib/python3.7/site-packages/Florence/VariationalPrinciple/VariationalPrinciple.py", line 5, in <module>
    from .DisplacementApproachIndices import FillGeometricB
ModuleNotFoundError: No module named 'Florence.VariationalPrinciple.DisplacementApproachIndices'

**Comment by nicolaskr** [comment]
The installation works with ubuntu 16.04 but on 18.04 the issue is present.

**Comment by romeric** [comment]
It seems like the installation has not been successful. Is this under a virtual environment? I have no issues with 18.04.

**Comment by nicolaskr** [comment]
It is not a a virtual environment.
The installation on an another machine, with the same steps, on ubuntu 16.04 has worked.

I will retry on the first machine (18.04).

**Comment by nicolaskr** [comment]
Retried on ubuntu 18.04, with conda environment and without.

The same error appears when runnig " From Florence import * "

" /home/user/.local/lib/python3.6/site-packages/Florence/FiniteElements/Assembly/_LowLevelAssembly_.py:24: UserWarning: Cannot use low level dispatchers for Assembly
  warn("Cannot use low level dispatchers for Assembly")
/home/user/.local/lib/python3.6/site-packages/Florence/FiniteElements/Assembly/_LowLevelAssembly_.py:32: UserWarning: Cannot use low level dispatchers for Assembly
  warn("Cannot use low level dispatchers for Assembly")
/home/user/.local/lib/python3.6/site-packages/Florence/FiniteElements/Assembly/_LowLevelAssembly_.py:39: UserWarning: Cannot use low level dispatchers for Assembly
  warn("Cannot use low level dispatchers for Assembly")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/Florence/__init__.py", line 6, in <module>
    from .VariationalPrinciple import *
  File "/home/user/.local/lib/python3.6/site-packages/Florence/VariationalPrinciple/__init__.py", line 1, in <module>
    from .VariationalPrinciple import *
  File "/home/user/.local/lib/python3.6/site-packages/Florence/VariationalPrinciple/VariationalPrinciple.py", line 5, in <module>
    from .DisplacementApproachIndices import FillGeometricB
ModuleNotFoundError: No module named 'Florence.VariationalPrinciple.DisplacementApproachIndices' "

**Comment by romeric** [comment]
This is an installation issue and may have been caused due to ABI incompatibility. `DisplacementApproachIndices` is an extension module and if it can't be found it means it was not built. Can you instead do:

~~~
pip install Florence -v
~~~
or
~~~
pip install Florence -vvv
~~~

and report the build log here?

**Comment by nicolaskr** [comment]
It's working 
I did not have BLAS installed on the ubuntu 18.04 machine

sudo apt-get install libopenblas-dev   solved the problem

The error was clear when running python setup.py build:

fatal error: cblas.h: no such file or directory
 #include <cblas.h>
